---
- name: Make autoload directory
  file: path=~/.vim/autoload state=directory

- name: Make bundle directory
  file: path=~/.vim/bundle state=directory

- name: Get Pathogen
  get_url: url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

- name: Vim Solarized
  git: repo=git://github.com/altercation/vim-colors-solarized.git dest=~/.vim/bundle/vim-colors-solarized

